### ISSUE TITLE
几点 review 建议

### ISSUE THREAD

**Issue by atian25** [fomenyesu/egg-mongodb-example#1]
- run 目录要配置下 .gitignore，这个是运行时的数据
- 建议用 `egg-init --type=simple .` 来初始化项目
- ` "egg-view-react": "^0.0.1",` 没用到不用引入
- config 里面有很多没用到的可以删掉

**Comment by fomenyesu** [comment]
感谢大神的建议，删除了一些无用代码逻辑，感觉清爽很多。
后面补充上supertest的测试逻辑。

**Comment by atian25** [comment]
- `newsType.js` 这类命名建议改为 `news_type` 或 `NewsType`，因为它本身不是实例，请求时才会实例化为 `this.service.newsType` 和 `this.controller.newsType`
- `public/Thumbs.db`
- `news/list.tpl` 这些应该用不到的吧，等等地方。

**Comment by fomenyesu** [comment]
已经补充上supertest的测试逻辑
