### ISSUE TITLE
POST,  "error": "Cannot read property 'uid' of null"

### ISSUE THREAD

**Issue by weizeng** [fomenyesu/egg-mongodb-example#2]
POST /api/users/ HTTP/1.1
Host: localhost:7001
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 971a5a87-55c5-6f79-d755-e8ce9a9aa309

{"uid":2,"name":"admin123","pass":"123","status":1,"time":"1325472736"}

response:

{
  "error": "Cannot read property 'uid' of null"
}

**Comment by fomenyesu** [comment]
需要加一个用于自增ID的Collection名字为IdGenerator里面加一个Document：
{
    "_id" : ObjectId("592069937092ebaddbdcbc5b"),
    "modelName" : "counter",
    "uid" : 1,
    "tid" : 0,
    "nid" : 0
}

**Comment by Gala-1024** [comment]
我也遇到这个错误。请问怎么解决

**Comment by Gala-1024** [comment]
必须要先在数据库的所有文档里面增加一些data.json的数据，才可以吗？

**Comment by fomenyesu** [comment]
不是。只需加一个用于自增ID的Collection名字为IdGenerator里面加一个Document：
{
"_id" : ObjectId("592069937092ebaddbdcbc5b"),
"modelName" : "counter",
"uid" : 1,
"tid" : 0,
"nid" : 0
}
到数据库里就可以了。

**Comment by Gala-1024** [comment]
好的，可以了。
谢谢
