### ISSUE TITLE
index()的分页效果请求方法

### ISSUE THREAD

**Issue by phper-chen** [fomenyesu/egg-mongodb-example#4]
http://127.0.0.1:7001/user/users?p=3&o=4    index方法里面打印的是{}，也就是说index方法拿不到参数，如果不能实现分页效果，那么这个resource是有点鸡肋的啊
我的错，换成this.query就可以查到了

**Comment by fomenyesu** [comment]
egg使用的是koa框架。请求参数 get默认使用 this.query获取参数。
