### ISSUE TITLE
MIME type ('text/html') is not a supported stylesheet MIME type

### ISSUE THREAD

**Issue by rocwong-cn** [fomenyesu/egg-mongodb-example#5]
大佬你好！
下载你的项目后运行报错：
``` js
Refused to apply style from 'http://localhost:7001/index.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
刚学习eggjs，不知道是不是什么地方配置的不对呀，感谢感谢！

**Comment by fomenyesu** [comment]
这个项目主要是用来提供后端 REST API 的。
没有做界面开发。所以界面应该是打不开的。如果需要包含后台界面的整套开发。
可以使用：

[https://github.com/fomenyesu/egg-restapi-module-tool](https://github.com/fomenyesu/egg-restapi-module-tool)

进行后台开发。谢谢关注！
